### ISSUE TITLE
npm install fails at `node-pre-gyp install --fallback-to-build=false || make`

### ISSUE THREAD

**Issue by psychoveter** [ricepo/isodist#1]
Stack trace: 

> osrm@5.6.3 install D:\projects\cargo\isodist\node_modules\osrm
> node-pre-gyp install --fallback-to-build=false || make

node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/osrm/v5.6.3/Release/node-v48-win32-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (D:\projects\cargo\isodist\node_modules\osrm\node_modules\node-pre-gyp\lib\install.js:120:27)
node-pre-gyp ERR! stack     at emitOne (events.js:101:20)
node-pre-gyp ERR! stack     at Request.emit (events.js:188:7)
node-pre-gyp ERR! stack     at Request.onRequestResponse (D:\projects\cargo\isodist\node_modules\osrm\node_modules\request\request.js:1074:10)
node-pre-gyp ERR! stack     at emitOne (events.js:96:13)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:188:7)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:474:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:363:20)
node-pre-gyp ERR! stack     at emitOne (events.js:96:13)
node-pre-gyp ERR! System Windows_NT 10.0.14393
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\projects\\cargo\\isodist\\node_modules\\osrm\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build=false"
node-pre-gyp ERR! cwd D:\projects\cargo\isodist\node_modules\osrm
node-pre-gyp ERR! node -v v6.9.5
node-pre-gyp ERR! node-pre-gyp -v v0.6.33
node-pre-gyp ERR! not ok
403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/osrm/v5.6.3/Release/node-v48-win32-x64.tar.gz
"make" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Asus\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! osrm@5.6.3 install: `node-pre-gyp install --fallback-to-build=false || make`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the osrm@5.6.3 install script 'node-pre-gyp install --fallback-to-build=false || make'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the osrm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build=false || make
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs osrm
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls osrm
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\projects\cargo\isodist\npm-debug.log

Environment: 
Windows 10 64b
node --version
v6.9.5
npm --version
3.10.9

**Comment by jluchiji** [comment]
Hi,

Sorry but this project was developed for use on Linux/MacOS, and was never intended to work on Windows. One major reason being dependency on [node-osrm](https://github.com/Project-OSRM/node-osrm). 

From your logs, it looks npm tried to download Windows binary for that module and failed. When it tried to build from source, it looks like you did not have C/C++ toolchain installed:

> "make" не является внутренней или внешней
> командой, исполняемой программой или пакетным файлом.

Please try it in a Unix environment, or consult documentation of node-osrm and make sure you have correct dependencies in your Windows environment.

P.S. You might also need to build [osrm-backend](https://github.com/Project-OSRM/osrm-backend) from source, since you need it to preprocess OSM data files. Please refer to `script/setup.sh` and `script/prepare.sh` for more information.

**Comment by jobryant** [comment]
It seems that there's no supports for osrm-node building under win-platform since 5.x version.
It's OK, if you change the 'win' into 'linux' as following:
https://mapbox-node-binary.s3.amazonaws.com/osrm/v5.6.3/Release/node-v48-linux-x64.tar.gz
